---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "npm"
    directory: "/src/client"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
